.TH r.area 1 "" "GRASS 7.2.2" "Grass User's Manual"
.SH NAME
\fI\fBr.area\fR\fR  \- Calculates area of clumped areas and remove areas smaller than given threshold.
.SH KEYWORDS
raster, statistics, area
.SH SYNOPSIS
\fBr.area\fR
.br
\fBr.area \-\-help\fR
.br
\fBr.area\fR [\-\fBb\fR] \fBinput\fR=\fIname\fR \fBoutput\fR=\fIname\fR  [\fBlesser\fR=\fIinteger\fR]   [\fBgreater\fR=\fIinteger\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-b\fR" 4m
.br
Binary output
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of cell category map, e.g., maps created with r.clump
.IP "\fBoutput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Map with area size (in cells)
.IP "\fBlesser\fR=\fIinteger\fR" 4m
.br
Remove areas lower than (0 for none):
.br
Default: \fI0\fR
.IP "\fBgreater\fR=\fIinteger\fR" 4m
.br
Remove areas greater than (\-1 for none):
.br
Default: \fI\-1\fR
.SH OPTIONS
.IP "\fBinput\fR" 4m
.br
Name of input created with r.clump or another cell category map.
.IP "\fBtreshold\fR" 4m
.br
Remove areas smaller than treshold, set null for removing areas
.IP "\fBbinary\fR" 4m
.br
Output map has only 0 and 1 values. If treshold is applied small areas are emoved and replaced by 0
.IP "\fBoutput\fR" 4m
.br
Original categories replaced with number of cells for each category. If areas belonging to category are not continuous every area belonging to the same category has the same area value.
.SH DESCRIPTION
.PP
module can be used to remove, areas smaller than treshold, reclass according areas (similar to r.reclass area, but work in cells, not hectares and allow create more classes)
.SH SEE ALSO
\fI
r.clump,
r.mapcalc,
r.reclass.area
\fR
.SH AUTHOR
Jarek  Jasiewicz
.SH SOURCE CODE
.PP
Available at: r.area source code (history)
.PP
Main index |
Raster index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2017
GRASS Development Team,
GRASS GIS 7.2.2 Reference Manual
