.TH v.transects 1 "" "GRASS 7.2.2" "Grass User's Manual"
.SH NAME
\fI\fBv.transects\fR\fR  \- Creates transect lines or quadrilateral areas at regular intervals perpendicular to a polyline.
.SH KEYWORDS
vector, transect
.SH SYNOPSIS
\fBv.transects\fR
.br
\fBv.transects \-\-help\fR
.br
\fBv.transects\fR [\-\fBl\fR] \fBinput\fR=\fIname\fR \fBoutput\fR=\fIname\fR \fBtransect_spacing\fR=\fIfloat\fR  [\fBdleft\fR=\fIfloat\fR]   [\fBdright\fR=\fIfloat\fR]   [\fBtype\fR=\fIstring\fR]   [\fBmetric\fR=\fIstring\fR]   [\fBtransect_perpendicular\fR=\fIstring\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-l\fR" 4m
.br
Use the last point of the line to create transect
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of input vector map
.br
Or data source for direct OGR access
.IP "\fBoutput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name for output vector map
.IP "\fBtransect_spacing\fR=\fIfloat\fR \fB[required]\fR" 4m
.br
Transect spacing along input polyline
.IP "\fBdleft\fR=\fIfloat\fR" 4m
.br
Distance transect extends to the left of input line
.br
Default is the same as the transect spacing
.IP "\fBdright\fR=\fIfloat\fR" 4m
.br
Distance transect extends to the right of input line
.br
Default is the same as the transect spacing
.IP "\fBtype\fR=\fIstring\fR" 4m
.br
Input feature type
.br
Options: \fIpoint, line, area\fR
.br
Default: \fIline\fR
.IP "\fBmetric\fR=\fIstring\fR" 4m
.br
Determines how transect spacing is measured
.br
Options: \fIstraight,  along\fR
.br
Default: \fIstraight\fR
.br
\fBstraight\fR: Straight distance between transect points
.br
\fBalong\fR: Distance along the line
.IP "\fBtransect_perpendicular\fR=\fIstring\fR" 4m
.br
Determines which line is the transect perpendicular to
.br
Options: \fItrend,  line\fR
.br
Default: \fItrend\fR
.br
\fBtrend\fR: Perpendicular to the line connecting transect points
.br
\fBline\fR: Perpendicular to the particular segment of the original line
.SH DESCRIPTION
\fIv.transects\fR creates equally spaced geometries along
input lines. Depending on the selected \fBmetric\fR, the distances
are measured either as straight distances between the transects or along the line.
Straight distance is better when the lines are complicated (shorelines)
and using the distance along line would result in big differences in the transect spacing.
.PP
The geometries can be lines or quadrilateral areas. Lines
and areas are generated to be perpendicular to either the input line
(select \fIline\fR for parameter \fBtransect_perpendicular\fR),
or to the line connecting the transect points
(select \fItrend\fR for parameter \fBtransect_perpendicular\fR).
The latter option is useful for complicated lines, because it follows the trend of the line.
.PP
By default the last point of each line is not used
because the last transect distance would be typically different from the previous once.
To create a transect from the last point, use flag \fB\-l\fR.
.PP
The following pictures show the effect of different options on a line with simple geometry.
In the first picture, the circles show points generated by v.segment
in 100 m interval along the line. The green lines were generated with option
\fCmetric=along\fR, therefore they match with the points. The blue lines
were generated with \fCmetric=straight\fR.
.br
In the second picture, green lines use \fCtransect_perpendicular=line\fR
while the blue ones use \fCtransect_perpendicular=trend\fR.
.SH NOTES
Input vector lines that are shorter than \fBtransect_spacing\fR are ignored.
.PP
\fBtransect_spacing\fR, \fBdleft\fR, and \fBdright\fR are interpreted
to be in horizontal map units (e.g., degrees in the LatLong/WGS84 coordinate system).
.PP
\fI\fBv.transects\fR\fR may fail for a network of lines in Windows.
.SH EXAMPLES
In these examples, the
Nags Head (19MB)
mapset is used to generate a shoreline and shore\-perpendicular geometries. To use the mapset, unpack it into the
nc_spm_08_grass7 (50MB)
location.
.SS Example 1) \- Generate line transects along shoreline
.PP
Generate 20 cross\-shore transects along 2008 shoreline (1m contour)
.br
.br
.nf
\fC
g.region raster=NH_2008_1m
r.contour input=NH_2008_1m output=NH_2008_1m level=1 cut=100
v.report map=NH_2008_1m option=length
# cat|level|length
# 1|1|1037.86684790028
# 1038m / 20transects = 52m per transect (value for transect_spacing)
v.transects input=NH_2008_1m output=NH_2008_transects transect_spacing=52
v.info NH_2008_transects
\fR
.fi
.SS Example 2) \- Generate line transects specifying the left and right length
.PP
Generate longer, more parallel transects by specifying dleft and dright and
smoothing the input line
.br
.br
.nf
\fC
g.region raster=NH_2008_1m
r.contour input=NH_2008_1m output=NH_2008_1m level=1 cut=100
v.generalize input=NH_2008_1m output=NH_2008_1m_smoothed \(rs
  method=sliding_averaging look_ahead=201
v.transects input=NH_2008_1m_smoothed \(rs
  output=NH_2008_transects_long_smoothed transect_spacing=52 \(rs
  dleft=20 dright=300
\fR
.fi
.SS Example 3) \- Generate area transects along shoreline
.PP
Generate longer, more parallel transects by specifying dleft and dright and
smoothing the input line
.br
.br
.nf
\fC
g.region raster=NH_2008_1m
r.contour input=NH_2008_1m output=NH_2008_1m level=1 cut=100
v.transects input=NH_2008_1m output=NH_2008_areas \(rs
  transect_spacing=52 dleft=20 dright=300 type=area
v.db.addtable NH_2008_areas
v.db.addcolumn map=NH_2008_areas columns=\(cqdemStats DOUBLE PRECISION\(cq
v.rast.stats vector=NH_2008_areas raster=NH_2008_1m column_prefix=NH2008
v.db.select NH_2008_areas
\fR
.fi
.SH SEE ALSO
v.segment
.br
v.generalize
.br
v.transects tutorial
.SH AUTHOR
Eric Hardin, Helena Mitasova, Updates by John Lloyd
.PP
\fILast changed: $Date: 2015\-01\-11 03:48:53 +0000 (Sun, 11 Jan 2015) $\fR
.SH SOURCE CODE
.PP
Available at: v.transects source code (history)
.PP
Main index |
Vector index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2017
GRASS Development Team,
GRASS GIS 7.2.2 Reference Manual
